export const terms = [
    { term: 'ARM', video: './ASL_Videos/arm_rutgers.mp4' },
    { term: 'BACK', video: './ASL_Videos/back_rutgers.mp4' },
    { term: 'CHEST', video: './ASL_Videos/chest_rutgers.mp4' },
    { term: 'EARS', video: './ASL_Videos/ear.mp4' },
    { term: 'EYES', video: './ASL_Videos/eyes_rutgers.mp4' },
    { term: 'HEAD', video: './ASL_Videos/head_rutgers.mp4' },
    { term: 'JAW', video: './ASL_Videos/jaw_rutgers.mp4' },
    { term: 'KNEES', video: './ASL_Videos/knees_rutgers.mp4' },
    { term: 'NOSE', video: './ASL_Videos/nose_rutgers.mp4' },
    { term: 'RIBS', video: './ASL_Videos/ribs_rutgers.mp4' },
    { term: 'STOMACH', video: './ASL_Videos/stomach_rutgers.mp4' },
    { term: 'THROAT', video: './ASL_Videos/throat_rutgers.mp4' },
    { term: 'SCRAPE', video: './ASL_Videos/scrape_rutgers.mp4' },
    { term: 'STAB', video: './ASL_Videos/stab_rutgers.mp4' },
    { term: 'STITCH', video: './ASL_Videos/stitch_rutgers.mp4' },
    { term: 'CUT', video: './ASL_Videos/cut_rutgers.mp4' },
    { term: 'BURN', video: './ASL_Videos/burn_rutgers.mp4' },
    { term: 'DIZZY', video: './ASL_Videos/dizzy_rutgers.mp4' },
    { term: 'FAINT', video: './ASL_Videos/faint_rutgers.mp4' },
    { term: 'HEADACHE', video: './ASL_Videos/headache_rutgers.mp4' },
    { term: 'ITCH', video: './ASL_Videos/itch_rutgers.mp4' },
    { term: 'STOMACH CRAMPS', video: './ASL_Videos/stomachcramps_rutgers.mp4' },
    { term: 'PANIC', video: './ASL_Videos/panic_rutgers.mp4' },
    { term: 'RASH', video: './ASL_Videos/rash_rutgers.mp4' },
    { term: 'SWEATING', video: './ASL_Videos/sweating_rutgers.mp4' },
    { term: 'SWELLING', video: './ASL_Videos/swelling_rutgers.mp4' },
    { term: 'VOMIT', video: './ASL_Videos/vomit_rutgers.mp4' },
    { term: 'ALCOHOL', video: './ASL_Videos/alcohol_rutgers.mp4' },
    { term: 'COCAINE', video: './ASL_Videos/cocaine_rutgers.mp4' },
    { term: 'DRUG', video: './ASL_Videos/drug_rutgers.mp4' },
    { term: 'MARIJUANA', video: './ASL_Videos/marijuana_rutgers.mp4' },
    { term: 'OVERDOSE', video: './ASL_Videos/overdose_rutgers.mp4' }

];